### ISSUE TITLE
Consolidated Azure Spring Apps BOM

### ISSUE THREAD

**Issue by bryandx** [Azure/Azure-Spring-Apps#47]
We're starting to deploy Spring apps to Azure Spring Apps.  We are utilizing Azure Key Vault in our Spring Apps running in Azure Spring Apps.   In our Maven pom, we've had to include 2 Azure Spring BOMs.  I have some comments of the web sites where I found the BOM's referenced. It would be nice if they were combined into a single BOM.   If there is a way to just include a single BOM already, please let me know.

	<dependencyManagement>
		<dependencies>
			
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>2021.0.7</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency> 
					
		    <dependency>
		      	<groupId>com.azure.spring</groupId>
		      	<artifactId>spring-cloud-azure-dependencies</artifactId>
		      	<version>4.7.0</version>
		      	<type>pom</type>
		      	<scope>import</scope>
		    </dependency>			
		</dependencies>
	</dependencyManagement>

**Can we contact you for additional details?** Y

**Comment by allxiao** [comment]
Hi @bryandx ,

The two BOMs include different dependency definitions.
* `spring-cloud-dependencies` contains the Spring Boot and Spring Cloud dependencies
* `spring-cloud-azure-dependencies` contains the dependencies for Azure integration with Spring Cloud

They were not combined together so that the users can choose to include different Spring Boot capabilities on demand, for example, switch to a different vault implementation.
